src/entries/urls.py
from django.urls import path

from . import views

app_name = "entries"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:entry_id>/", views.detail, name="detail"),
]

src/feeds/urls.py
from django.urls import path

from . import views

app_name = "feeds"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("curated", views.curated, name="curated"),
    path("all", views.all, name="all"),
    path("<int:feed_item_id>/", views.detail, name="detail"),
    path("feed", views.list_feeds, name="list_feeds"),
    path("feed/<int:feed_id>/all", views.feed_all, name="feed_all"),
    path("feed/<int:feed_id>/curated", views.feed_curated, name="feed_curated"),
    path("api/like/<int:feed_item_id>/", views.api_like, name="api_like"),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('entries/', include('entries.urls')),
    path('', include('feeds.urls')),
    path('admin/', admin.site.urls),
]

src/entries/models.py
from django.db import models


class Entry(models.Model):
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

src/feeds/models.py
from django.db import models

# This is the model to describe how the rss/atom xml for a specific feed maps to Item
class ItemFeedMap(models.Model):
    item_feed_map_name = models.CharField(max_length=200)
    items = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    item_id = models.CharField(max_length=200)
    published = models.CharField(max_length=200)
    updated = models.CharField(max_length=200)
    content = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    image_url = models.CharField(max_length=200)

    def __str__(self):
        return self.item_feed_map_name

class FeedCategory(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)  # optional description field

    def __str__(self):
        return self.name

# This is the model for the feed, e.g. for https://konstellationen.org/atom.xml
class Feed(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    item_feed_map = models.ForeignKey(ItemFeedMap, on_delete=models.CASCADE)
    category = models.ForeignKey(FeedCategory, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

# This describes a generic rss/atom feed item
class Item(models.Model):
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    # These are things related to the moderation on this site
    date_processed = models.DateTimeField("date processed", null=True)
    show_item = models.BooleanField(default=False)
    imported = models.DateTimeField("date imported", null=True)

    # The following fields are fields taken from the rss/atom feed
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    item_id = models.CharField(max_length=200)
    published = models.DateTimeField("date published", null=True, blank=True)
    updated = models.DateTimeField("date updated", null=True, blank=True)
    content = models.TextField(blank=True)
    summary = models.TextField(blank=True)
    image_url = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return "{} - {}".format(self.feed, self.title)

src/entries/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Entry

def index(request):
    latest_entry_list = Entry.objects.order_by("-pub_date")[:5]
    context = {
        "latest_entry_list": latest_entry_list,
    }
    return render(request, "entries/index.html", context)

def detail(request, entry_id):
    entry = get_object_or_404(Entry, pk=entry_id)
    return render(request, "entries/detail.html", {"entry": entry})

src/feeds/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone

from datetime import timedelta

from .models import Item
from .models import Feed
from .models import FeedCategory

def index(request):
    now = timezone.now()
    # We will only allow liked articles to be on top for 3 days
    some_time_ago = now - timedelta(days=3)
    latest_processed_items_to_show = Item.objects.filter(show_item=True, published__gte=some_time_ago).order_by("-published")[:20]
    latest_item_list = Item.objects.exclude(show_item=True, published__gte=some_time_ago).order_by("-published")[:40]
    context = {
        "latest_processed_items_to_show": latest_processed_items_to_show,
        "latest_item_list": latest_item_list,
    }
    return render(request, "index.html", context)

def about(request):
    return render(request, "about.html", {})

def contact(request):
    return render(request, "contact.html", {})

def all(request):
    item_list = Item.objects.all().order_by("-published")
    # 50 per page
    paginator = Paginator(item_list, 50)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "feed/index.html", {
        "feed_type": "all",
        "page_obj": page_obj,
    })

def curated(request):
    item_list = Item.objects.filter(show_item=True).order_by("-published")
    # 50 per page
    paginator = Paginator(item_list, 50)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "feed/index.html", {
        "feed_type": "curated",
        "page_obj": page_obj,
    })

def feed_all(request, feed_id):
    # Attempt to get the feed for the ID and 404 if we can't find it.
    feed = get_object_or_404(Feed, pk=feed_id)

    # Retrieve feed items for a specific feed, ordered by the published date with the most recent ones first.
    items = Item.objects.filter(feed_id=feed_id).order_by("-published")

    # Paginate the feed's items with 50 items per page.
    paginator = Paginator(items, 50)

    # Use the URL query parameter "page" to select which page to show.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, "feed/index.html", {
        "feed_type": "all",
        "feed": feed,
        "page_obj": page_obj
    })

def feed_curated(request, feed_id):
    # Attempt to get the feed for the ID and 404 if we can't find it.
    feed = get_object_or_404(Feed, pk=feed_id)

    # Retrieve feed items for a specific feed, ordered by the published date with the most recent ones first.
    # Also filter the items based on "show_item" which determines if it's curated or not.
    items = Item.objects.filter(feed_id=feed_id, show_item=True).order_by("-published")

    # Paginate the feed's items with 50 items per page.
    paginator = Paginator(items, 50)

    # Use the URL query parameter "page" to select which page to show.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, "feed/index.html", {
        "feed_type": "curated",
        "feed": feed,
        "page_obj": page_obj
    })

def detail(request, feed_item_id):
    item = get_object_or_404(Item, pk=feed_item_id)
    return render(request, "feed/item.html", {"item": item})

def list_feeds(request):
    categories = FeedCategory.objects.prefetch_related('feed_set').all()
    return render(request, "feeds/index.html", {"categories": categories})

@csrf_exempt
def api_like(request, feed_item_id):
    if request.method != "POST":
        return JsonResponse({'success': False,'message':'Method not allowed'}, status=405)

    if not request.user.is_authenticated:
        return JsonResponse({'success': False,'message':'Not logged in'}, status=401)
    
    try:
        item = Item.objects.get(pk=feed_item_id)
        print("item")
        print(item)
        item.show_item = True
        item.date_processed = timezone.now()
        item.save()

        return JsonResponse({'success': True,'message':'Like successful'})

    except Item.DoesNotExist as e:
        return JsonResponse({'success': False,'message':'Item does not exist'}, status=404)

    except Exception as e:
        print("e")
        print(e)
        return JsonResponse({'success': False,'message':'Unknown error occured when liking'}, status=500)
    

src/entries/templates/entries/detail.html
<h1>{{ entry.title }}</h1>
<ul>
    <li>{{ entry.url }}</li>
    <li>{{ entry.pub_date }}</li>
</ul>

src/entries/templates/entries/index.html
{% if latest_entry_list %}
    <ul>
    {% for entry in latest_entry_list %}
        <li>
            <a href="{{ entry.url }}">{{ entry.title }}</a><br/>
            <a href="{% url 'entries:detail' entry.id %}">Info</a><br/>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No entries are available.</p>
{% endif %}

src/feeds/templates/_menu.html
<nav class="py-6 px-6 md:px-0 flex bg-omni-white border-b flex-col md:flex-row justify-between md:items-center">
    <a href="/" class="block text-2xl font-black flex gap-2 no-underline">
        <div class="mt-2 w-4 h-4 bg-omni-red rounded-full"></div>
        Mediakollen
    </a>
    
    <ul class="flex items-center gap-3 text-light">
        {% include "_menu_item.html" with title="Om sidan" url_name='feeds:about' %}
        {% include "_menu_item.html" with title="Flöden" url_name='feeds:list_feeds' %}
        {% include "_menu_item.html" with title="Kontakt" url_name='feeds:contact' %}
    </ul>
</nav>

src/feeds/templates/_menu_item.html
<li><a class="no-underline" href="{% url url_name %}">{{ title }}</a></li>

src/feeds/templates/about.html
{% extends "base.html" %}

{% block content %}
<div id="page-content" class="my-9 px-6 md:px-0">
    <h1 class="text-3xl font-extrabold my-6">Om sidan</h1>
    <p>
        Den här sidan hämtar nyheter från en rad källor och visar några utvalda.
        Ett projekt av <a href="https://konstellationen.org">Kamratdataföreningen Konstellationen</a>.
    </p>
</div>
{% endblock %}

src/feeds/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Mediakollen{% endblock %}</title>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="True">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <link rel='stylesheet' href='{% static 'style.css' %}' media='all' />
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', (e) => {
            document.querySelectorAll('button[data-button-action="like"]').forEach((item) => {
                item.addEventListener('click', (e) => {
                    const button = e.target.closest('button');
                    const itemId = button.dataset.item_id;
                    const xmlhtt = new XMLHttpRequest();
                    const url = `/api/like/${itemId}/`;
                    xmlhtt.open("POST", url, true);
                    xmlhtt.setRequestHeader("Content-Type", "application/json");
                    xmlhtt.send(null);
                    xmlhtt.onreadystatechange = () => {
                        if (xmlhtt.readyState == 4 && xmlhtt.status == 200) {
                            try {
                                const jsonData = JSON.parse(xmlhtt.responseText);
                                if (jsonData.success) {
                                    item.setAttribute("disabled", "disabled");
                                    item.innerHTML = "Gillat och klart";
                                } else {
                                    console.error("Error occured with json data");
                                    console.error(jsonData);
                                }
                            } catch (error) {
                                console.error("Error occured");
                                console.error(error);
                            }
                        }
                    };

                });
            });
        });
    </script>
</head>

<body class="bg-omni-white font-sans">
    <div class="flex w-full items-center flex-col">
        <div class="max-w-3xl w-full">
            {% include "_menu.html" %}
            <div class="" id="content">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

src/feeds/templates/contact.html
{% extends "base.html" %}

{% block content %}

<div id="page-content" class="my-9 px-6 md:px-0">
    <h1 class="text-3xl font-extrabold my-6">Kontakt</h1>
    <p>
        Vill du komma i kontakt med oss så maila <a href="mailto:kamratadata@proton.me">kamratadata@proton.me</a>.
        Du kan följa <a href="https://social.spejset.org/@konstellationen">Kamratdataföreningen Konstellationens mastodonkonto</a>.
    </p>
</div>
{% endblock %}

src/feeds/templates/feed/_item.html
{% load humanize %}
<li class="item flex flex-row gap-3 justify-start items-start">
    <div class="text-sm">
        <div class="dott w-2 h-2 bg-omni-red rounded-full"></div>
    </div>
    <div class="flex flex-col gap-1 pr-6">
        <div class="flex flex-row justify-self-start items-center gap-2 text-sm"><time class="font-semibold">{{ item.published|naturaltime }}</time><a href="{% url 'feeds:feed_curated' item.feed_id %}" class="no-underline hover:underline font-light">{{ item.feed.name }}</a></div>
        <a target="_blank" title="{{ item.title }}" class="no-underline hover:underline font-extrabold leading-tight" href="{{ item.link }}">
            {{ item.title }}
        </a>
        {% if user.is_authenticated %}
            {% if not item.show_item %}
                <div class="meta">
                    <button class="flex flex-row items-center justify-start gap-1 text-semibold text-sm cursor-pointer" data-button-action="like" data-item_id="{{ item.id }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                        </svg>
                        <span>Gilla</span>
                    </button>
                </div>
            {% endif %}
        {% endif %}
    </div>
</li>

src/feeds/templates/feed/index.html
{% extends "base.html" %}

{% block content %}

 <ul class="flex flex-col gap-6 border-b">
     <li class="flex flex-row justify-between items-center border-b pl-8 pr-6 md:pr-0 py-3 sticky top-0 bg-omni-white">
         <div>
             {% if feed_type == 'all' %}
                 Alla
             {% elif feed_type == 'curated' %}
                 Utvalda
             {% else %}
                 {{ feed_type|capfirst }}
             {% endif %}
             {% if feed %} artiklar från {{ feed.name }}
             {% else %} artiklar
             {% endif %}
         </div>
         <div class="text-sm flex flex-row gap-3">
             {% if feed %}
                 <a class="{% if feed_type == 'curated' %}text-omni-red underline{% endif %} hover:underline" href="{% url 'feeds:feed_curated' feed.id %}">Utvalda</a>
                 <a class="{% if feed_type == 'all' %}text-omni-red underline{% endif %} hover:underline" href="{% url 'feeds:feed_all' feed.id %}">Alla</a>
             {% else %}
                 <a class="{% if feed_type == 'curated' %}text-omni-red underline{% endif %} hover:underline" href="{% url 'feeds:curated' %}">Utvalda</a>
                 <a class="{% if feed_type == 'all' %}text-omni-red underline{% endif %} hover:underline" href="{% url 'feeds:all' %}">Alla</a>
             {% endif %}
         </div>
     </li>
    {% for item in page_obj %}
        {% include "feed/_item.html" with item=item %}
    {% endfor %}
</ul>

<div class="pagination my-6 px-6 md:px-0">
    <span class="step-links flex flex-row justify-start items-center gap-3 text-sm">
        {% if page_obj.has_previous %}
            <a href="?page=1">Första</a>
            <a href="?page={{ page_obj.previous_page_number }}">Föregående</a>
        {% endif %}

        <span class="current">
            Sida {{ page_obj.number }} av {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Nästa</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Sista</a>
        {% endif %}
    </span>
</div>
{% endblock %}

src/feeds/templates/feed/item.html
{% extends "base.html" %} {% block content %}
<h1>{{ item.title }}</h1>
<ul>
  <li>{{ item.link }}</li>
  <li>{{ item.published }}</li>
  <li>{{ item.summary }}</li>
</ul>
{% endblock %}

src/feeds/templates/feeds/_feed.html
<li class="px-6 md:px-0">
  {{ feed.category.name }}
  <a
    class="underline pb-1 text-sm"
    href="{% url 'feeds:feed_curated' feed.id %}"
    >{{ feed.name }}</a
  >
</li>

src/feeds/templates/feeds/index.html
{% extends "base.html" %} {% block content %}

<ul class="flex flex-col gap-6 border-b">
  <li class="border-b px-6 md:px-0 py-3 sticky top-0 bg-omni-white">
    <h3 class="text-base font-light">Alla tillgängliga flöden</h3>
    <p class="m-0 text-sm">
      Här kan du se alla tillgängliga flöden, gå till ett flöde för att se alla
      inlägg i det.
    </p>
  </li>

  {% for category in categories %}
  <li>
    <h3 class="text-base font-light">{{ category.name }}</h3>
    <ul>
      {% for feed in category.feed_set.all %}
      <li>
        <a
          class="underline pb-1 text-sm"
          href="{% url 'feeds:feed_curated' feed.id %}"
          >{{ feed.name }}</a
        >
      </li>
      {% endfor %}
    </ul>
    {% endfor %}
  </li>
</ul>

{% endblock %}

src/feeds/templates/index.html
{% extends "base.html" %}

{% block content %}

{% if latest_processed_items_to_show %}
    <ul class="flex flex-col gap-6 border-b">
        <li class="border-b px-8 py-3 sticky top-0 bg-omni-white">
            <h3 class="text-base font-light">Senaste utvalda artiklar</h3>
        </li>
        {% for item in latest_processed_items_to_show %}
            {% include "feed/_item.html" with item=item %}
        {% endfor %}
        <li class="px-8 mb-9">
            <a href="{% url 'feeds:curated' %}" class="underline hover:no-underline text-sm">Visa alla utvalda artiklar</a>
        </li>
    </ul>
{% endif %}

{% if latest_item_list %}
    <ul class="flex flex-col gap-6">
        <li class="border-b px-8 py-3 sticky top-0 bg-omni-white">
            <h3 class="text-base font-light">Senaste övriga artiklar</h3>
        </li>
        {% for item in latest_item_list %}
            {% include "feed/_item.html" with item=item %}
        {% endfor %}
        <li class="px-8 mb-9">
            <a href="{% url 'feeds:all' %}" class="underline hover:no-underline text-sm">Visa alla övriga artiklar</a>
        </li>
    </ul>
{% else %}
    <p>No feed items are available.</p>
{% endif %}
{% endblock %}